basePath: /
host: localhost:8080
info:
  contact:
    email: giabao.vonguyen@gmail.com
    name: API Support
    url: http://www.capigiba.com/support
  description: API documentation for Trinity App
  title: Trinity App API
  version: "1.0"
paths: {}
swagger: "2.0"
